import { defineCollection, z } from 'astro:content';
import { glob } from 'astro/loaders';

// Topic pages are generated by `scripts/ingest.mjs` into src/content/topics/.
const topics = defineCollection({
  loader: glob({ pattern: '*.md', base: './src/content/topics' }),
  schema: z.object({
    title: z.string(),
    course: z.string(),
    order: z.number(),
    slug: z.string(),
    summary: z.string(),
    viz: z.array(z.string()).default([]),
  }),
});

export const collections = { topics };
